# Generated by Django 5.0.6 on 2025-03-19 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name_plural': 'Scholarships'},
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
